##
# Generating all p-values from a null model based on PrePPI 200M interactions database hosted on a Neo4j server
# -------------------------------------------------------------------------------------------------------------

require(RNeo4j)

## Loading Functions ----
message(">>> Loading PrePPI Libraries")
source("libs/preppi-libs.R")

## Setting Neo4j Credential ----
neo4j_username <- "neo4j"
neo4j_password <- "preppi"
neo4j_server_url <- "http://localhost:7474/db/data/"

## Filename Declaration ----
preppi_final600_filename <- "utils/data/preppi_final600.txt"
ppi_cache_filename <- "tmp/searchin_ppi_cache_table_Jul9_2019.csv"

if (!.isNeo4jServerOffline)
{
	## Attaching Neo4j web handle ----
	message(">>> Attaching Neo4j web handle @ " , neo4j_server_url , " as user: ", neo4j_username )
	graph = startGraph( neo4j_server_url , username = neo4j_username , password = neo4j_password )          
}

## Loading datasets and caches ----
message(">>> Reading the PrePPI DB with good scores - LH > 0.5 ")
	preppi_dt <- fread(preppi_final600_filename)
message(">>> Loading cache | PPI pvalues already computed from a null models | e.g. the ones generated by previous runs")  
	ppi_cache <- load_ppi_cache(ppi_cache_filename)

preppi_obj <- new("PrePPIClass", name = "debugging" , preppi_dt = preppi_dt , cache_table = ppi_cache )
	
runPreppiModel <- function( ligand_uniprot_id , receptor_uniprot_id )
{
	
	preppi_filtered <- preppi_dt[ prot1 %in% unique(ligand_uniprot_id) & prot2 %in% unique(receptor_uniprot_id) , ]

	system.time({
		message("- Generating PValue / Null Model for " ,  nrow(preppi_filtered) , " PPIs ...")
		preppi_filtered$preppi_empirical_pvalue <- purrr::pmap_dbl(  .l = list( p1 = preppi_filtered$prot1 , 
			p2 = preppi_filtered$prot2 ) , .f = getPrePPIScoresFromGDB , preppi_obj = preppi_obj , debug = FALSE )
		tmp <- as_tibble(preppi_filtered) %>% dplyr::select(prot1,prot2,preppi_empirical_pvalue) %>% dplyr::rename(p1=prot1,p2=prot2,pvalue=preppi_empirical_pvalue)
		# print(tmp)
		preppi_obj@cache_table <- bind_rows( list(preppi_obj@cache_table , tmp) )
		preppi_obj@cache_table <- preppi_obj@cache_table %>% distinct()
		store_ppi_cache( preppi_obj@cache_table , ppi_cache_filename )
		
	})
	
	return(preppi_obj@cache_table)
	
} # End of runPreppiModel

